flusswerk:
  processing:
    maxRetries: 5
    threads: 5
  connection:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  routing:
    exchange: my.exchange
    readFrom: queue.to.read.from
    writeTo: defalt.queue.to.write.to