spring:
  application:
    name: flusswerk.demo

flusswerk:
  processing:
    maxRetries: 5
    threads: 5
  connection:
    connectTo: localhost:5672
    username: guest
    password: guest
  routing:
    exchange: my.exchange
    readFrom: queue.to.read.from
    writeTo: defalt.queue.to.write.to
  monitoring:
    prefix: workflow