include: "https://raw.githubusercontent.com/dbmdz/development/master/ci/.gitlab-ci-base.yml"

cache:
  key: "$CI_COMMIT_SHA"
  paths:
    - engine/target/
    - examples-plain/target/
    - examples-spring-boot/target/
    - spring-boot-starter-flusswerk/target/
    - integration-test/target/

services:
  - "$DIND_IMAGE"

variables:
  DOCKER_HOST: tcp://docker:2375/

.integration_tests:
  script:
    - docker-compose up -d
    - mvn clean install
    - mvn -B --projects integration-tests -Pintegration -Dspring.profiles.active=$MAVEN_ACTIVE_PROFILE surefire:test
  stage: test
  variables:
    RABBIT_HOST: docker

integration_tests:openjdk11:
  extends: .integration_tests
  image: "$BUILD_IMAGE_ANSIBLE_MAVEN_JDK11"

integration_tests:openjdk12:
  extends: .integration_tests
  image: "$BUILD_IMAGE_ANSIBLE_MAVEN_JDK12"
  only:
    variables:
      - $USE_OPENJDK12