language: java
jdk:
- openjdk8
- oraclejdk8
- oraclejdk9
sudo: required
services:
- docker
before_script:
- if [ ! -z "$TRAVIS_TAG" ]; then mvn versions:set -DnewVersion=$TRAVIS_TAG; fi
script:
- mvn clean install
- mvn -B --projects bdd -Pbdd surefire:test
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: dmwwzsBM1yD1MTgQNfF4VXSN117L44nffgiLyzTboMlZucXwGdW2MSXynIuO4DnF1sZrSN3XA82W9QsGEPVW3AJwaTRf9+AhQvkQqjNQH4kvrYH51q0GhKa+JwhO2V/7qHnOqP92mFRk4U2PLgqHirILRfJYqvTdDJBzakQZ5PD5PY8rXgh+QS7LMV8Zygf8ifYFA9fgjstlpCIcovgT8yF+WyUkRiRN9LR5H6Mt/YiEkpQJKsdwDfM+ClyzcRO/U2AE1whe9gLvv83aIPRyvheItY4/XNwJ8qDxLoDhyERWMahqoc4b7RyVbivsLztyScTEDg3sUYii9Y/tEUrQ6zFuozxTvknagbAYLI/YxDiPZpdx8gKpTMR7D0aEoYbVqyODDjyQOoHdaIaSYAPZ7ILaEjv6VN4QEYfDH6XTAd/6lYmsdnl/MH7L6h37k5CKtejAsKasMqFk1qITODgOmepQtqtmhfEn+6U2W/fp8sWJJj+9j/k321lAT1yRBqScQNcED63XCLJYtYIFnL4A92HTU2XLaEovWurj0Gf2EU1wPMZWFDC270f8MKdBTC7pfM3MLe4v0OdGLqRv0XEBQZ0k4wLXr7nkLVjf8mfF2+SsXYoaqA/gtC4XNr3iII3Eu3YOt/fJCDID8YIcAPOUoXBAajOdVsc6oGZ5OVVYVuE=
  file_glob: true
  file:
  - "**/target/*.jar"
  skip_cleanup: true
  on:
    tags: true
  body: $TRAVIS_COMMIT_MESSAGE
