# Spring Boot common application properties (https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)
spring:
  profiles:
    active: local
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: workflow

# Application specific properties (having no pendant in common properties)
messageBroker:
  deadLetterExchange: workflow.dlx
  queues:
    read: someInputQueue
    write: someOutputQueue

---

spring:
  profiles: ci
  rabbitmq:
    host: docker