on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    env:
      MAVEN_OPTS: " --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
      --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
      --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
      --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
      --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED "
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v2
        env:
          cache-name: cache-maven-artifacts
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Build with Maven
        run: mvn -B -Pintegration verify
    services:
      rabbitmq:
        image: rabbitmq:3-alpine
        ports:
          - 5672:5672
      redis:
        image: redis
        ports:
          - 6379:6379
  publish:
    if: (github.event_name == 'push' && contains(github.ref, 'main')) || github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        env:
          cache-name: cache-maven-artifacts
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Install XML utils
        run: sudo apt install libxml2-utils
      - name: Set project version
        run: echo "PROJECT_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)" >> $GITHUB_ENV
      # Publish snapshot
      - name: Set up JDK 11 for publishing a snapshot
        if: github.event_name == 'push' && endswith(env.PROJECT_VERSION, 'SNAPSHOT')
        uses: actions/setup-java@v2
        with:
          java-version: 11
          server-id: ossrh-snapshots
          server-password: MAVEN_PASSWORD
          server-username: MAVEN_USERNAME
      - name: Publish snapshot to the Maven Central Repository
        if: github.event_name == 'push' && endswith(env.PROJECT_VERSION, 'SNAPSHOT')
        run: mvn -B deploy -P maven-central
        env:
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      # Publish release
      - name: Set up JDK 11 for publishing a release
        if: github.event_name == 'release' && !endswith(env.PROJECT_VERSION, 'SNAPSHOT')
        uses: actions/setup-java@v2
        with:
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          java-version: 11
          server-id: ossrh
          server-password: MAVEN_PASSWORD
          server-username: MAVEN_USERNAME
      - name: Publish release to the Maven Central Repository
        if: github.event_name == 'release' && !endswith(env.PROJECT_VERSION, 'SNAPSHOT')
        run: mvn -B deploy -P maven-central
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
